import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue.shade800)),
      home: const MyHomePage(title: 'Decoration of Container'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(backgroundColor: Theme.of(context).colorScheme.inversePrimary, title: Text(widget.title)),
      body:
          // --> here gap is generated by transparent containers.
          Container(
            width: double.infinity,
            height: double.infinity,
            color: Colors.purple.shade200,
            child: Column(
              children: [
                Container(width: 10, height: 10, decoration: BoxDecoration(color: Colors.white)), //--> gap
                Container(
                  width: 100,
                  height: 100,
                  decoration: BoxDecoration(color: Colors.purple.shade500, borderRadius: BorderRadius.circular(21)),
                ),
                Container(width: 10, height: 10, decoration: BoxDecoration(color: Colors.white)),
                Container(
                  width: 100,
                  height: 100,
                  decoration: BoxDecoration(
                    color: Colors.purple.shade500,
                    borderRadius: BorderRadius.only(topLeft: Radius.circular(21), bottomRight: Radius.circular(21)),
                  ),
                ),
                Container(width: 10, height: 10, decoration: BoxDecoration(color: Colors.white)),
                Container(
                  width: 100,
                  height: 100,
                  decoration: BoxDecoration(
                    color: Colors.purple.shade500,
                    borderRadius: BorderRadius.only(topRight: Radius.circular(21), bottomLeft: Radius.circular(21)),
                    border: Border.all(width: 2, color: Colors.black),
                  ),
                ),
                Container(width: 10, height: 10, decoration: BoxDecoration(color: Colors.white)),
                Container(
                  width: 100,
                  height: 100,
                  decoration: BoxDecoration(
                    color: Colors.purple.shade500,
                    borderRadius: BorderRadius.circular(11),
                    boxShadow: [BoxShadow(blurRadius: 7, color: Colors.purple.shade500, spreadRadius: 2)],
                  ),
                ),
                Container(width: 10, height: 10, decoration: BoxDecoration(color: Colors.white)),
                Container(
                  width: 100,
                  height: 100,
                  decoration: BoxDecoration(
                    color: Colors.purple.shade500,
                    boxShadow: [BoxShadow(blurRadius: 7, color: Colors.black, spreadRadius: 3)],
                    shape: BoxShape.circle,
                  ),
                ),
              ],
            ),
          ),
    );
  }
}
